### ISSUE TITLE
StyleGuide generating theme YAML

### ISSUE THREAD

**Issue by pickert** [oroinc/OroCommerceStorefrontStyleGuide#1]
Thank you for the awesome work with this Sketch layout. I've been playing with it as you've been updating over the last few weeks! It's pretty amazing!

I do have a few questions, I've noticed the second row of Buttons are tied to a Button color scheme that is detached from the master 'Swatch' that most are tied to.. Is this something you're actively tying together over time?

Also, once the entire color scheme/palette has been defined and 'updated' throughout, how can I use the resulting colors within the OroCommerce theme YAML configuration files? Is there any sort of 'export' functionality that is within Sketch that I am just missing?

**Comment by vegadesign** [comment]
Hello @pickert 
Thank you for the feedback.

> I do have a few questions, I've noticed the second row of Buttons are tied to a Button color scheme that is detached from the master 'Swatch' that most are tied to.. Is this something you're actively tying together over time?

The second row of buttons has been made like "groups" (not as "symbols") to provide a better experience in customization (changing styles of states such as "default", "hover", "focused", etc.) for designers. So you do not need to open a page with "symbols", customize a state, then go back to "Elements & Controls" page and see the result. All you need is to make these changes in one place, update styles and see the result. 

![image](https://user-images.githubusercontent.com/8604229/75432209-c24b5d80-5956-11ea-94e6-e35bf9bb7496.png)

The same story with form elements ("inputs", "selectors", etc.). 

![image](https://user-images.githubusercontent.com/8604229/75432353-f6bf1980-5956-11ea-9023-9562f743505b.png)

Button states styles detached from the master 'Swatch', because the master 'Swatch' defines only colors and does not define styles of borders, shadows, etc.

>Also, once the entire color scheme/palette has been defined and 'updated' throughout, how can I use the resulting colors within the OroCommerce theme YAML configuration files? Is there any sort of 'export' functionality that is within Sketch that I am just missing?

Currently, there is no such kind of possibility as the export customized color scheme from the Sketch file to the OroCommerce theme configuration files.
